ZDOTDIR=~/.config/zsh
export EDITOR="nvim"

# Add all local binaries to the system path.
export PATH="${HOME}/.local/bin:${HOME}/.local/bin/private:/usr/local/opt/grep/libexec/gnubin:${PATH}"

# pnpm configuration.
export PNPM_HOME="${HOME}/Library/pnpm"
case ":${PATH}:" in
  *":${PNPM_HOME}:"*) ;;
  *) export PATH="${PNPM_HOME}:${PATH}" ;;
esac

# Antigravity configuration.
export PATH="${HOME}/.antigravity/antigravity/bin:${PATH}"

# Initialize Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Initialize FZF.
source <(fzf --zsh)

# Initialize thefuck.
eval $(thefuck --alias)

# nvm configuration.
export NVM_DIR="${HOME}/.config/nvm"

# Add grep to the path.
PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"